import React from 'react';
import { TrendingUp, Sparkles, Loader2, Share2, RefreshCw, Trophy, Target, Calendar, MessageSquare, CheckCircle2, BookOpen } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { supabase } from '../lib/supabase';
import { askGemini } from '../lib/gemini';

export default function ProgressReport() {
  const [report, setReport] = React.useState('');
  const [loading, setLoading] = React.useState(true);
  const [genLoading, setGenLoading] = React.useState(false);
  const [stats, setStats] = React.useState({
    aiSessions: 0,
    tasksCompleted: 0,
    totalTasks: 0,
    quizzesTaken: 0,
    flashcardSets: 0,
    summariesGenerated: 0,
    examsCount: 0,
    streak: 0,
    topCourse: 'N/A',
  });

  React.useEffect(() => {
    fetchStats();
  }, []);

  const fetchStats = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const lastWeek = new Date();
      lastWeek.setDate(lastWeek.getDate() - 7);
      const lastWeekStr = lastWeek.toISOString();

      const [
        { data: sessions },
        { data: progress },
        { data: allProgress },
        { data: quizzes },
        { data: flashcards },
        { data: exams },
        { data: profile },
      ] = await Promise.all([
        supabase.from('chat_sessions').select('course_code').eq('user_id', user.id).gte('updated_at', lastWeekStr),
        supabase.from('plan_progress').select('*').eq('user_id', user.id).eq('completed', true).gte('updated_at', lastWeekStr),
        supabase.from('plan_progress').select('*').eq('user_id', user.id),
        supabase.from('saved_quizzes').select('*').eq('user_id', user.id).gte('created_at', lastWeekStr),
        supabase.from('flashcard_sets').select('*').eq('user_id', user.id).gte('updated_at', lastWeekStr),
        supabase.from('user_exams').select('*').eq('user_id', user.id),
        supabase.from('profiles').select('study_streak, full_name').eq('id', user.id).maybeSingle(),
      ]);

      // Top course from sessions
      const focusMap: Record<string, number> = {};
      sessions?.forEach(s => {
        const code = s.course_code || 'General';
        focusMap[code] = (focusMap[code] || 0) + 1;
      });
      const topCourse = Object.entries(focusMap).sort((a, b) => b[1] - a[1])[0]?.[0] || 'N/A';

      setStats({
        aiSessions: sessions?.length || 0,
        tasksCompleted: progress?.length || 0,
        totalTasks: allProgress?.length || 0,
        quizzesTaken: quizzes?.length || 0,
        flashcardSets: flashcards?.length || 0,
        summariesGenerated: 0,
        examsCount: exams?.length || 0,
        streak: profile?.study_streak || 1,
        topCourse,
      });
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const generateReport = async () => {
    setGenLoading(true);
    setReport('');
    try {
      const prompt = `You are an encouraging but honest academic mentor for a Nigerian university student at Achievers University.

Here is their study activity this week:
- AI Tutor sessions: ${stats.aiSessions}
- Study tasks completed: ${stats.tasksCompleted}
- Quizzes taken: ${stats.quizzesTaken}
- Flashcard sets created: ${stats.flashcardSets}
- Current study streak: ${stats.streak} days
- Most studied course: ${stats.topCourse}
- Upcoming exams: ${stats.examsCount}

Generate a detailed weekly progress report with these sections:

📊 WEEKLY PERFORMANCE SUMMARY
A 3-4 sentence honest assessment of their week. Be specific about numbers.

💪 WHAT YOU DID WELL
3 specific strengths based on their activity this week.

⚠️ AREAS TO IMPROVE
3 specific areas they need to work on next week. Be direct.

🎯 NEXT WEEK ACTION PLAN
5 specific actions they should take next week to improve. Be very practical.

🏆 GRADE PREDICTION
Based on their current effort level, predict what grade they are on track for. Be honest but encouraging.

🔥 MOTIVATIONAL CLOSE
End with a short powerful motivational message in a Nigerian university student context. Reference hustle, exams, success.

Format with clear sections. Be specific, not generic.`;

      const response = await askGemini(prompt, 'Progress Report');
      setReport(response);
    } catch (err) {
      console.error(err);
    } finally {
      setGenLoading(false);
    }
  };

  const shareToWhatsApp = () => {
    if (!report) return;
    const text = `📊 *My Weekly Study Report — CourseGPT*\n\n🔥 Streak: ${stats.streak} days\n📚 AI Sessions: ${stats.aiSessions}\n✅ Tasks Done: ${stats.tasksCompleted}\n🧪 Quizzes: ${stats.quizzesTaken}\n\n${report.substring(0, 800)}...\n\n_Generated by CourseGPT 🎓_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const statCards = [
    { label: 'Study Streak', value: `${stats.streak} days`, icon: TrendingUp, color: 'bg-primary/10 text-primary' },
    { label: 'AI Sessions', value: stats.aiSessions, icon: MessageSquare, color: 'bg-purple-100 text-purple-600' },
    { label: 'Tasks Done', value: stats.tasksCompleted, icon: CheckCircle2, color: 'bg-success/10 text-success' },
    { label: 'Quizzes Taken', value: stats.quizzesTaken, icon: Trophy, color: 'bg-orange-100 text-orange-600' },
    { label: 'Flashcard Sets', value: stats.flashcardSets, icon: BookOpen, color: 'bg-blue-100 text-blue-600' },
    { label: 'Upcoming Exams', value: stats.examsCount, icon: Calendar, color: 'bg-error/10 text-error' },
  ];

  if (loading) return (
    <div className="animate-pulse space-y-6">
      <div className="h-10 w-64 bg-border rounded-lg" />
      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
        {[1,2,3,4,5,6].map(i => <div key={i} className="h-28 bg-border rounded-[2rem]" />)}
      </div>
    </div>
  );

  return (
    <div className="space-y-8">

      {/* Header */}
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-black text-text-primary tracking-tight flex items-center gap-3">
            <TrendingUp className="h-7 w-7 text-primary" /> Progress Report
          </h1>
          <p className="text-sm text-text-secondary mt-1 font-medium">
            Your weekly study performance — shareable to WhatsApp.
          </p>
        </div>
        <div className="flex items-center gap-2 bg-primary/10 px-4 py-2 rounded-xl border border-primary/10">
          <TrendingUp className="h-4 w-4 text-primary" />
          <span className="text-xs font-black text-primary uppercase tracking-widest">🔥 {stats.streak} Day Streak</span>
        </div>
      </header>

      {/* Stats Grid */}
      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
        {statCards.map((stat, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05 }}
            className="bg-white p-5 md:p-6 rounded-[2rem] border border-border shadow-sm"
          >
            <div className={`h-10 w-10 ${stat.color} rounded-2xl flex items-center justify-center mb-4`}>
              <stat.icon className="h-5 w-5" />
            </div>
            <div className="text-2xl font-black text-text-primary tracking-tighter">{stat.value}</div>
            <div className="text-[10px] font-black text-text-secondary uppercase tracking-widest mt-1">{stat.label}</div>
            <div className="text-[9px] text-text-secondary opacity-50 mt-0.5">This week</div>
          </motion.div>
        ))}
      </div>

      {/* Most studied course */}
      {stats.topCourse !== 'N/A' && (
        <div className="bg-primary p-6 rounded-[2rem] flex items-center justify-between shadow-xl shadow-primary/20">
          <div>
            <div className="text-white/60 text-[10px] font-black uppercase tracking-widest mb-1">Most Studied Course This Week</div>
            <div className="text-white font-black text-2xl tracking-tighter">{stats.topCourse}</div>
          </div>
          <Target className="h-12 w-12 text-white opacity-20" />
        </div>
      )}

      {/* Report Generator */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1">
          <div className="bg-white rounded-[2rem] border border-border p-6 shadow-sm space-y-4">
            <h2 className="text-xs font-black text-text-primary uppercase tracking-widest flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" /> AI Report
            </h2>
            <p className="text-xs text-text-secondary font-medium leading-relaxed">
              Generate a detailed AI analysis of your week with grade prediction, action plan and motivational message.
            </p>
            <button
              onClick={generateReport}
              disabled={genLoading}
              className="w-full py-4 bg-primary text-white font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-primary/90 transition-all flex items-center justify-center gap-2 shadow-xl shadow-primary/10 disabled:opacity-50"
            >
              {genLoading
                ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating...</>
                : <><Sparkles className="h-4 w-4" /> {report ? 'Regenerate' : 'Generate Report'}</>
              }
            </button>

            {report && (
              <div className="flex flex-col gap-2">
                <button
                  onClick={shareToWhatsApp}
                  className="w-full py-3 bg-green-500 text-white font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-green-600 transition-all flex items-center justify-center gap-2"
                >
                  <Share2 className="h-4 w-4" /> Share to WhatsApp
                </button>
                <button
                  onClick={generateReport}
                  disabled={genLoading}
                  className="w-full py-3 bg-bg border border-border text-text-secondary font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-white transition-all flex items-center justify-center gap-2 disabled:opacity-50"
                >
                  <RefreshCw className="h-4 w-4" /> Regenerate
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Report Display */}
        <div className="lg:col-span-2">
          {report ? (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white rounded-[2rem] border border-border shadow-sm overflow-hidden"
            >
              <div className="bg-gradient-to-r from-primary to-primary/80 p-6">
                <div className="text-white/60 text-[10px] font-black uppercase tracking-widest mb-1">Weekly Progress Report</div>
                <h2 className="text-white font-black text-xl tracking-tight">Your Study Analysis</h2>
                <p className="text-white/70 text-xs mt-1">
                  {new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toLocaleDateString('en-NG', { day: 'numeric', month: 'short' })} — {new Date().toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' })}
                </p>
              </div>
              <div className="p-6 md:p-8">
                <div className="whitespace-pre-wrap text-sm text-text-primary font-medium leading-relaxed">
                  {report}
                </div>
              </div>
            </motion.div>
          ) : (
            <div className="min-h-[400px] bg-white rounded-[2rem] border border-border flex flex-col items-center justify-center text-center p-12 shadow-sm">
              <AnimatePresence>
                {genLoading ? (
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-6 flex flex-col items-center">
                    <div className="h-20 w-20 bg-primary/10 rounded-[2rem] flex items-center justify-center animate-pulse">
                      <TrendingUp className="h-10 w-10 text-primary" />
                    </div>
                    <div>
                      <h3 className="text-2xl font-black text-text-primary mb-2 tracking-tighter">Analysing your week...</h3>
                      <p className="text-text-secondary text-sm font-medium">Crunching your study data and generating insights.</p>
                    </div>
                    <div className="flex space-x-2">
                      <div className="h-2 w-2 bg-primary rounded-full animate-pulse" />
                      <div className="h-2 w-2 bg-primary rounded-full animate-pulse [animation-delay:0.2s]" />
                      <div className="h-2 w-2 bg-primary rounded-full animate-pulse [animation-delay:0.4s]" />
                    </div>
                  </motion.div>
                ) : (
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
                    <div className="h-24 w-24 bg-bg rounded-[2rem] flex items-center justify-center mx-auto border-2 border-dashed border-border">
                      <TrendingUp className="h-12 w-12 text-text-secondary opacity-20" />
                    </div>
                    <div>
                      <h3 className="text-2xl font-black text-text-primary mb-2 tracking-tighter">See how you performed</h3>
                      <p className="text-text-secondary text-sm font-medium max-w-xs mx-auto">
                        Click Generate Report to get your AI-powered weekly analysis with grade prediction.
                      </p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}