import React from 'react';
import { FileText, Sparkles, Loader2, Share2, RefreshCw, BookOpen } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { supabase } from '../lib/supabase';
import { askGemini } from '../lib/gemini';
import Markdown from 'react-markdown';

export default function SummaryGenerator() {
  const [exams, setExams] = React.useState<any[]>([]);
  const [selectedExam, setSelectedExam] = React.useState<any>(null);
  const [summary, setSummary] = React.useState<string>('');
  const [loading, setLoading] = React.useState(true);
  const [genLoading, setGenLoading] = React.useState(false);

  React.useEffect(() => { fetchExams(); }, []);

  const fetchExams = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      const { data } = await supabase
        .from('user_exams')
        .select('*')
        .eq('user_id', user.id)
        .order('exam_date', { ascending: true });
      const withPdf = (data || []).filter((e: any) => e.pdf_url);
      setExams(withPdf);
      if (withPdf.length > 0) setSelectedExam(withPdf[0]);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const fetchPdfText = async (pdfUrl: string): Promise<string> => {
    try {
      const res = await fetch(pdfUrl);
      const arrayBuffer = await res.arrayBuffer();
      const bytes = new Uint8Array(arrayBuffer);
      let binary = '';
      for (let i = 0; i < bytes.byteLength; i++) {
        binary += String.fromCharCode(bytes[i]);
      }
      return btoa(binary);
    } catch {
      return '';
    }
  };

  const generateSummary = async () => {
    if (!selectedExam) return;
    setGenLoading(true);
    setSummary('');
    try {
      let prompt = '';
      if (selectedExam.pdf_url) {
        const pdfBase64 = await fetchPdfText(selectedExam.pdf_url);
        prompt = `You are helping a Nigerian university student at Achievers University prepare for their ${selectedExam.course_code} (${selectedExam.course_name}) exam on ${selectedExam.exam_date}.

Based on the course material provided, generate a comprehensive exam-focused summary using proper markdown formatting:

## 📌 Course Overview
2-3 sentences about what this course covers.

## 🔑 Key Concepts
List at least 8-10 most important topics with clear explanations. Use **bold** for key terms.

## 📝 Must-Know Definitions
At least 8 key terms and definitions. Format: **TERM** — definition

## ⚡ Likely Exam Topics
Top 5 topics most likely to appear with reasons. Use numbered list.

## 🧠 Quick Formulas / Rules
Important formulas or rules to memorize. Skip if not relevant.

## ✅ Last-Minute Checklist
5 things to review the night before the exam.

Use proper markdown: ## for headings, **bold** for important terms, - for bullet points, 1. for numbered lists.

PDF Content (base64): ${pdfBase64.substring(0, 3000)}`;
      } else {
        prompt = `You are helping a Nigerian university student at Achievers University prepare for their ${selectedExam.course_code} (${selectedExam.course_name}) exam on ${selectedExam.exam_date}. Difficulty: ${selectedExam.difficulty}.

Generate a comprehensive exam-focused summary using proper markdown formatting:

## 📌 Course Overview
2-3 sentences about what this course covers.

## 🔑 Key Concepts
List at least 8-10 most important topics with clear explanations. Use **bold** for key terms.

## 📝 Must-Know Definitions
At least 8 key terms and definitions. Format: **TERM** — definition

## ⚡ Likely Exam Topics
Top 5 topics most likely to appear with reasons. Use numbered list.

## 🧠 Quick Formulas / Rules
Important formulas or rules to memorize. Skip if not relevant.

## ✅ Last-Minute Checklist
5 things to review the night before the exam.

Use proper markdown: ## for headings, **bold** for important terms, - for bullet points, 1. for numbered lists.`;
      }
      const response = await askGemini(prompt, selectedExam.course_code);
      setSummary(response);
    } catch (err) {
      console.error(err);
    } finally {
      setGenLoading(false);
    }
  };

  const shareToWhatsApp = () => {
    if (!summary) return;
    const text = `📚 *${selectedExam?.course_code} Exam Summary*\n\n${summary}\n\n_Generated by CourseGPT 🎓_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  if (loading) return (
    <div className="animate-pulse space-y-6">
      <div className="h-10 w-64 bg-border rounded-lg" />
      <div className="h-96 bg-border rounded-[2rem]" />
    </div>
  );

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-2xl md:text-3xl font-black text-text-primary tracking-tight">Summary Generator</h1>
        <p className="text-sm text-text-secondary mt-1 font-medium">Get a 1-page exam-focused summary from your course PDF.</p>
      </header>

      {exams.length === 0 ? (
        <div className="bg-white rounded-[2rem] border border-border p-16 text-center shadow-sm">
          <div className="h-20 w-20 bg-bg rounded-[2rem] flex items-center justify-center mx-auto mb-6 border-2 border-dashed border-border">
            <BookOpen className="h-10 w-10 text-text-secondary opacity-20" />
          </div>
          <h3 className="text-xl font-black text-text-primary mb-2">No PDF uploaded yet</h3>
          <p className="text-sm text-text-secondary mb-6">Go to the Study Planner and upload a PDF for your exam.</p>
          <a href="/dashboard/planner" className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-white font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-primary/90 transition-all">
            Go to Planner → Upload PDF
          </a>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-1 space-y-4">
            <div className="bg-white rounded-[2rem] border border-border p-6 shadow-sm">
              <h2 className="text-xs font-black text-text-primary uppercase tracking-widest mb-4 flex items-center gap-2">
                <FileText className="h-4 w-4 text-primary" /> Select Exam
              </h2>
              <div className="space-y-2">
                {exams.map(exam => (
                  <button
                    key={exam.id}
                    onClick={() => { setSelectedExam(exam); setSummary(''); }}
                    className={`w-full text-left p-4 rounded-2xl border transition-all ${selectedExam?.id === exam.id ? 'bg-primary text-white border-primary' : 'bg-bg border-border hover:border-primary/40'}`}
                  >
                    <div className="flex items-center justify-between">
                      <div>
                        <div className={`font-black text-sm uppercase tracking-tight ${selectedExam?.id === exam.id ? 'text-white' : 'text-text-primary'}`}>{exam.course_code}</div>
                        <div className={`text-[10px] font-medium mt-0.5 truncate max-w-[160px] ${selectedExam?.id === exam.id ? 'text-white/70' : 'text-text-secondary'}`}>{exam.course_name || 'Achievers Course'}</div>
                      </div>
                      <span className={`text-[8px] font-black px-1.5 py-0.5 rounded-full uppercase ${selectedExam?.id === exam.id ? 'bg-white/20 text-white' : 'bg-primary/10 text-primary'}`}>PDF ✓</span>
                    </div>
                  </button>
                ))}
              </div>
              <button
                onClick={generateSummary}
                disabled={genLoading || !selectedExam}
                className="w-full mt-6 py-4 bg-primary text-white font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-primary/90 transition-all flex items-center justify-center gap-2 shadow-xl shadow-primary/10 disabled:opacity-50"
              >
                {genLoading ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating...</> : <><Sparkles className="h-4 w-4" /> {summary ? 'Regenerate' : 'Generate Summary'}</>}
              </button>
            </div>
          </div>

          <div className="lg:col-span-2">
            {summary ? (
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="bg-white rounded-[2rem] border border-border shadow-sm overflow-hidden">
                <div className="bg-primary p-6 flex items-center justify-between">
                  <div>
                    <div className="text-white/60 text-[10px] font-black uppercase tracking-widest mb-1">Exam Summary</div>
                    <h2 className="text-white font-black text-xl tracking-tight">{selectedExam?.course_code}</h2>
                    <p className="text-white/70 text-xs font-medium mt-0.5">{selectedExam?.course_name}</p>
                  </div>
                  <div className="bg-white/20 px-3 py-1 rounded-xl text-white text-[10px] font-black uppercase tracking-widest">
                    {new Date(selectedExam?.exam_date).toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' })}
                  </div>
                </div>
                <div className="p-6 md:p-8">
                  <div className="prose prose-sm max-w-none prose-headings:font-black prose-headings:text-text-primary prose-headings:tracking-tight prose-p:text-text-secondary prose-p:font-medium prose-strong:text-text-primary prose-li:text-text-secondary prose-li:font-medium prose-h2:text-lg prose-h2:mt-6 prose-h2:mb-3">
                    <Markdown>{summary}</Markdown>
                  </div>
                </div>
                <div className="p-6 border-t border-border flex flex-col sm:flex-row gap-3">
                  <button onClick={shareToWhatsApp} className="flex-1 py-4 bg-green-500 text-white font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-green-600 transition-all flex items-center justify-center gap-2">
                    <Share2 className="h-4 w-4" /> Share to WhatsApp
                  </button>
                  <button onClick={generateSummary} disabled={genLoading} className="flex-1 py-4 bg-bg border border-border text-text-primary font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-white transition-all flex items-center justify-center gap-2 disabled:opacity-50">
                    <RefreshCw className="h-4 w-4" /> Regenerate
                  </button>
                </div>
              </motion.div>
            ) : (
              <div className="h-full min-h-[500px] bg-white rounded-[2rem] border border-border flex flex-col items-center justify-center text-center p-12 shadow-sm">
                <AnimatePresence>
                  {genLoading ? (
                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-6 flex flex-col items-center">
                      <div className="h-20 w-20 bg-primary/10 rounded-[2rem] flex items-center justify-center animate-pulse">
                        <Sparkles className="h-10 w-10 text-primary" />
                      </div>
                      <div>
                        <h3 className="text-2xl font-black text-text-primary mb-2 tracking-tighter">Building your summary...</h3>
                        <p className="text-text-secondary text-sm font-medium">Reading your PDF and extracting key exam topics.</p>
                      </div>
                      <div className="flex space-x-2">
                        <div className="h-2 w-2 bg-primary rounded-full animate-pulse" />
                        <div className="h-2 w-2 bg-primary rounded-full animate-pulse [animation-delay:0.2s]" />
                        <div className="h-2 w-2 bg-primary rounded-full animate-pulse [animation-delay:0.4s]" />
                      </div>
                    </motion.div>
                  ) : (
                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
                      <div className="h-24 w-24 bg-bg rounded-[2rem] flex items-center justify-center mx-auto border-2 border-dashed border-border">
                        <FileText className="h-12 w-12 text-text-secondary opacity-20" />
                      </div>
                      <div>
                        <h3 className="text-2xl font-black text-text-primary mb-2 tracking-tighter">Ready to summarize</h3>
                        <p className="text-text-secondary text-sm font-medium max-w-xs mx-auto">Select an exam and click Generate Summary.</p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}