import React from 'react';
import { FileText, Sparkles, Loader2, Share2, RefreshCw, BookOpen, FileUp, X } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { supabase } from '../lib/supabase';
import { askGemini } from '../lib/gemini';
import { extractTextFromFile } from '../lib/pdfExtract';
import Markdown from 'react-markdown';

export default function SummaryGenerator() {
  const [exams, setExams] = React.useState<any[]>([]);
  const [selectedExam, setSelectedExam] = React.useState<any>(null);
  const [summary, setSummary] = React.useState<string>('');
  const [loading, setLoading] = React.useState(true);
  const [genLoading, setGenLoading] = React.useState(false);
  const [pdfFile, setPdfFile] = React.useState<File | null>(null);
  const [pdfText, setPdfText] = React.useState('');
  const [pdfLoading, setPdfLoading] = React.useState(false);

  React.useEffect(() => { fetchExams(); }, []);

  const fetchExams = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      const { data } = await supabase
        .from('user_exams').select('*').eq('user_id', user.id)
        .order('exam_date', { ascending: true });
      setExams(data || []);
      if (data && data.length > 0) setSelectedExam(data[0]);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handlePdfUpload = async (file: File) => {
    setPdfFile(file);
    setPdfLoading(true);
    setPdfText('');
    try {
      const { text } = await extractTextFromFile(file);
      setPdfText(text);
    } catch (err) {
      console.error('PDF read error:', err);
    } finally {
      setPdfLoading(false);
    }
  };

  const generateSummary = async () => {
    if (!selectedExam) return;
    setGenLoading(true);
    setSummary('');
    try {
      const hasPdf = pdfText.length > 100;
      const prompt = hasPdf
        ? `You are helping a Nigerian university student at Achievers University prepare for their ${selectedExam.course_code} (${selectedExam.course_name}) exam on ${selectedExam.exam_date}.

Generate a comprehensive exam-focused summary STRICTLY based on the following course material only:

"""
${pdfText.substring(0, 4000)}
"""

Use proper markdown formatting:

## 📌 Course Overview
2-3 sentences about what this course covers based on the material above.

## 🔑 Key Concepts
List at least 8-10 most important topics from the material. Use **bold** for key terms.

## 📝 Must-Know Definitions
At least 8 key terms and definitions from the material. Format: **TERM** — definition

## ⚡ Likely Exam Topics
Top 5 topics from this material most likely to appear in the exam.

## 🧠 Quick Formulas / Rules
Important formulas or rules from the material. Skip if not in the material.

## ✅ Last-Minute Checklist
5 things to review based on this material.`
        : `You are helping a Nigerian university student at Achievers University prepare for their ${selectedExam.course_code} (${selectedExam.course_name}) exam on ${selectedExam.exam_date}. Difficulty: ${selectedExam.difficulty}.

Generate a comprehensive exam-focused summary using proper markdown:

## 📌 Course Overview
## 🔑 Key Concepts
## 📝 Must-Know Definitions
## ⚡ Likely Exam Topics
## 🧠 Quick Formulas / Rules
## ✅ Last-Minute Checklist

Use **bold** for key terms, - for bullets, 1. for numbered lists.`;

      const response = await askGemini(prompt, selectedExam.course_code);
      setSummary(response);
    } catch (err) {
      console.error(err);
    } finally {
      setGenLoading(false);
    }
  };

  const shareToWhatsApp = () => {
    if (!summary) return;
    const text = `📚 *${selectedExam?.course_code} Exam Summary*\n\n${summary}\n\n_Generated by CourseGPT 🎓_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  if (loading) return (
    <div className="animate-pulse space-y-6">
      <div className="h-10 w-64 bg-border rounded-lg" />
      <div className="h-96 bg-border rounded-[2rem]" />
    </div>
  );

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-2xl md:text-3xl font-black text-text-primary tracking-tight">Summary Generator</h1>
        <p className="text-sm text-text-secondary mt-1 font-medium">Upload your course PDF and get a 1-page exam-focused summary.</p>
      </header>

      {exams.length === 0 ? (
        <div className="bg-white rounded-[2rem] border border-border p-16 text-center shadow-sm">
          <div className="h-20 w-20 bg-bg rounded-[2rem] flex items-center justify-center mx-auto mb-6 border-2 border-dashed border-border">
            <BookOpen className="h-10 w-10 text-text-secondary opacity-20" />
          </div>
          <h3 className="text-xl font-black text-text-primary mb-2">No exams added yet</h3>
          <p className="text-sm text-text-secondary mb-6">Go to the Study Planner and add your exams first.</p>
          <a href="/dashboard/planner" className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-white font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-primary/90 transition-all">Go to Planner</a>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-1 space-y-4">
            <div className="bg-white rounded-[2rem] border border-border p-6 shadow-sm space-y-5">

              {/* PDF Upload */}
              <div>
                <label className="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-2 block">Upload Course PDF</label>
                <label className={`flex items-center gap-3 w-full px-4 py-4 border-2 border-dashed rounded-2xl cursor-pointer transition-all ${pdfFile ? pdfLoading ? 'border-primary/40 bg-primary/5' : 'border-success bg-success/5' : 'border-border bg-bg hover:border-primary'}`}>
                  <input type="file" accept=".pdf" className="hidden" onChange={e => { const f = e.target.files?.[0]; if (f && f.type === 'application/pdf') handlePdfUpload(f); }} />
                  {pdfLoading ? (
                    <><Loader2 className="h-4 w-4 text-primary animate-spin shrink-0" /><span className="text-xs font-black text-primary uppercase tracking-widest">Reading PDF...</span></>
                  ) : pdfFile ? (
                    <>
                      <FileText className="h-4 w-4 text-success shrink-0" />
                      <div className="flex-1 overflow-hidden">
                        <p className="text-xs font-black text-success uppercase tracking-widest truncate">{pdfFile.name}</p>
                        <p className="text-[10px] text-success/70 mt-0.5">{pdfText.length > 0 ? `✓ Ready` : 'Processing...'}</p>
                      </div>
                      <button type="button" onClick={e => { e.preventDefault(); setPdfFile(null); setPdfText(''); }} className="p-1 hover:text-error transition-colors shrink-0"><X className="h-4 w-4" /></button>
                    </>
                  ) : (
                    <><FileUp className="h-4 w-4 text-text-secondary shrink-0" /><span className="text-xs font-bold text-text-secondary">Click to upload PDF</span></>
                  )}
                </label>
              </div>

              {/* Exam selector */}
              <div>
                <label className="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-2 block">Select Exam</label>
                <div className="space-y-2">
                  {exams.map(exam => (
                    <button key={exam.id} onClick={() => { setSelectedExam(exam); setSummary(''); }} className={`w-full text-left p-4 rounded-2xl border transition-all ${selectedExam?.id === exam.id ? 'bg-primary text-white border-primary' : 'bg-bg border-border hover:border-primary/40'}`}>
                      <div className={`font-black text-sm uppercase tracking-tight ${selectedExam?.id === exam.id ? 'text-white' : 'text-text-primary'}`}>{exam.course_code}</div>
                      <div className={`text-[10px] font-medium mt-0.5 truncate ${selectedExam?.id === exam.id ? 'text-white/70' : 'text-text-secondary'}`}>{exam.course_name || 'Achievers Course'}</div>
                    </button>
                  ))}
                </div>
              </div>

              <div className={`p-3 rounded-xl border ${pdfText ? 'bg-primary/5 border-primary/20' : 'bg-orange-50 border-orange-200'}`}>
                <p className={`text-[10px] font-black uppercase tracking-widest ${pdfText ? 'text-primary' : 'text-orange-600'}`}>
                  {pdfText ? '📄 Summary will be generated from your PDF' : '⚠️ Upload a PDF for an accurate summary'}
                </p>
              </div>

              <button onClick={generateSummary} disabled={genLoading || !selectedExam || pdfLoading} className="w-full py-4 bg-primary text-white font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-primary/90 transition-all flex items-center justify-center gap-2 shadow-xl shadow-primary/10 disabled:opacity-50">
                {genLoading ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating...</> : <><Sparkles className="h-4 w-4" /> {summary ? 'Regenerate' : 'Generate Summary'}</>}
              </button>
            </div>
          </div>

          <div className="lg:col-span-2">
            {summary ? (
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="bg-white rounded-[2rem] border border-border shadow-sm overflow-hidden">
                <div className="bg-primary p-6 flex items-center justify-between">
                  <div>
                    <div className="text-white/60 text-[10px] font-black uppercase tracking-widest mb-1">Exam Summary</div>
                    <h2 className="text-white font-black text-xl tracking-tight">{selectedExam?.course_code}</h2>
                    <p className="text-white/70 text-xs font-medium mt-0.5">{selectedExam?.course_name}</p>
                  </div>
                  <div className="bg-white/20 px-3 py-1 rounded-xl text-white text-[10px] font-black uppercase tracking-widest">
                    {new Date(selectedExam?.exam_date).toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' })}
                  </div>
                </div>
                <div className="p-6 md:p-8">
                  <div className="prose prose-sm max-w-none prose-headings:font-black prose-headings:text-text-primary prose-headings:tracking-tight prose-p:text-text-secondary prose-p:font-medium prose-strong:text-text-primary prose-li:text-text-secondary prose-li:font-medium prose-h2:text-lg prose-h2:mt-6 prose-h2:mb-3">
                    <Markdown>{summary}</Markdown>
                  </div>
                </div>
                <div className="p-6 border-t border-border flex flex-col sm:flex-row gap-3">
                  <button onClick={shareToWhatsApp} className="flex-1 py-4 bg-green-500 text-white font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-green-600 transition-all flex items-center justify-center gap-2">
                    <Share2 className="h-4 w-4" /> Share to WhatsApp
                  </button>
                  <button onClick={generateSummary} disabled={genLoading} className="flex-1 py-4 bg-bg border border-border text-text-primary font-black text-xs uppercase tracking-widest rounded-2xl hover:bg-white transition-all flex items-center justify-center gap-2 disabled:opacity-50">
                    <RefreshCw className="h-4 w-4" /> Regenerate
                  </button>
                </div>
              </motion.div>
            ) : (
              <div className="h-full min-h-[500px] bg-white rounded-[2rem] border border-border flex flex-col items-center justify-center text-center p-12 shadow-sm">
                <AnimatePresence>
                  {genLoading ? (
                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-6 flex flex-col items-center">
                      <div className="h-20 w-20 bg-primary/10 rounded-[2rem] flex items-center justify-center animate-pulse">
                        <Sparkles className="h-10 w-10 text-primary" />
                      </div>
                      <div>
                        <h3 className="text-2xl font-black text-text-primary mb-2 tracking-tighter">Building your summary...</h3>
                        <p className="text-text-secondary text-sm font-medium">Reading your PDF and extracting key exam topics.</p>
                      </div>
                      <div className="flex space-x-2">
                        <div className="h-2 w-2 bg-primary rounded-full animate-pulse" />
                        <div className="h-2 w-2 bg-primary rounded-full animate-pulse [animation-delay:0.2s]" />
                        <div className="h-2 w-2 bg-primary rounded-full animate-pulse [animation-delay:0.4s]" />
                      </div>
                    </motion.div>
                  ) : (
                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
                      <div className="h-24 w-24 bg-bg rounded-[2rem] flex items-center justify-center mx-auto border-2 border-dashed border-border">
                        <FileText className="h-12 w-12 text-text-secondary opacity-20" />
                      </div>
                      <div>
                        <h3 className="text-2xl font-black text-text-primary mb-2 tracking-tighter">Ready to summarize</h3>
                        <p className="text-text-secondary text-sm font-medium max-w-xs mx-auto">Upload your PDF, select an exam and click Generate Summary.</p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}